site_name: Bloons TD Batttles 2 Wiki
site_url: https://github.com/Round8/BTDB2-Wiki

repo_name: Round8/BTDB2-Wiki
repo_url: https://github.com/Round8/BTDB2-Wiki

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.instant

  palette:
    primary: red
    accent: red
    scheme: slate
    
extra_css:
  - stylesheets/extra.css

use_directory_urls: false

nav:
  - Home: index.md
  - Resources: resources.md
  - Guides: 
    - Mod Guide: guides/mod-guide.md
     
